import { ReportDef } from '../models/sales-report.models';

/**
 * Auto-generated registry of the legacy 999-order reports, recreated on the
 * generic tabular engine. Each entry is a config the TabularReportPage renders.
 * Regenerate with: node gen-registry.cjs <workflow-output.json>
 */
export const REPORT_REGISTRY: Record<string, ReportDef> = {
  "salesPeriod": {
    id: "salesPeriod",
    titleEn: "Sales Period", titleAr: "مبيعات الفترة",
    subtitleEn: "Totals per day", subtitleAr: "إجماليات لكل يوم",
    endpoint: "DailySalesController/getDailySalesReport", transform: "groupByDate",
    rowsKey: "reportData", totalsKey: "totals",
    defaultOrdersFilter: "Paid",
    rowUnitEn: "days", rowUnitAr: "يوم",
    filters: ["payment", "transaction", "shift", "discount", "promo", "voucher", "onlineApp", "user", "waiter", "pilot"],
    columns: [
      { key: "orderDate", labelEn: "Date", labelAr: "التاريخ", type: "date" },
      { key: "ordersCount", labelEn: "Orders", labelAr: "عدد الطلبات", type: "int", totalKey: "ordersCount" },
      { key: "guestNo", labelEn: "Guests", labelAr: "عدد الضيوف", type: "int", totalKey: "guestNo" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money", totalKey: "totalSales" },
      { key: "totalCommercialDiscount", labelEn: "Commercial Discount", labelAr: "الخصم التجاري", type: "money", totalKey: "totalCommercialDiscount" },
      { key: "totalItemDiscount", labelEn: "Item Discount", labelAr: "خصم الأصناف", type: "money", totalKey: "totalItemDiscount" },
      { key: "extraDiscount", labelEn: "Extra Discount", labelAr: "خصم إضافي", type: "money", totalKey: "extraDiscount" },
      { key: "services", labelEn: "Services", labelAr: "الخدمة", type: "money", totalKey: "services" },
      { key: "totalTax", labelEn: "Tax", labelAr: "الضريبة", type: "money", totalKey: "totalTax" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cash" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visa" },
      { key: "cl", labelEn: "Ledge", labelAr: "آجل", type: "money", totalKey: "cl" },
      { key: "voucherAmount", labelEn: "Voucher", labelAr: "قسيمة", type: "money", totalKey: "voucherAmount" },
      { key: "otherPayment", labelEn: "Other Payment", labelAr: "دفع آخر", type: "money", totalKey: "otherPayment" },
      { key: "total", labelEn: "Total", labelAr: "الإجمالي الكلي", type: "money", totalKey: "total" },
      { key: "net", labelEn: "Net Amount", labelAr: "صافي المبلغ", type: "money", totalKey: "net" },
      { key: "totalExpenses", labelEn: "Total Expenses", labelAr: "إجمالي المصروفات", type: "money", totalKey: "totalExpenses" },
    ],
    mergeByDate: {
      endpoint: "reports/expenses/totals-by-date",
      rowsKey: "totals",
      srcDateKey: "date",
      srcValueKey: "totalAmount",
      dstDateKey: "orderDate",
      dstKey: "totalExpenses",
    },
    paymentSummary: {
      rows: [
        { key: "cash", labelEn: "Cash", labelAr: "نقدي", totalKey: "cash", always: true },
        { key: "visa", labelEn: "Visa", labelAr: "فيزا", totalKey: "visa", always: true },
        { key: "cl", labelEn: "Ledge", labelAr: "آجل", totalKey: "cl" },
        { key: "other", labelEn: "Other", labelAr: "دفع آخر", totalKey: "otherPayment" },
      ],
    },
    // Legacy receipt: Date · Sub Total · Service · Tax · Discount · Net.
    receiptColumns: [
      { key: "orderDate", en: "Date", ar: "التاريخ" },
      { key: "totalSales", en: "Sub Total", ar: "الإجمالي" },
      { key: "services", en: "Service", ar: "خدمة" },
      { key: "totalTax", en: "Tax", ar: "ضريبة" },
      { key: "totalCommercialDiscount", en: "Discount", ar: "خصم" },
      { key: "net", en: "Net", ar: "الصافي" },
    ],
  },
  "sales-period-by-transaction": {
    id: "sales-period-by-transaction",
    titleEn: "Sales Period By Transaction", titleAr: "مبيعات الفترة حسب نوع المعاملة",
    subtitleEn: "Totals per day × transaction type", subtitleAr: "إجماليات لكل يوم × نوع المعاملة",
    endpoint: "DailySalesController/getDailySalesReport", transform: "groupByDayTransaction",
    mergeColumn: "orderDate",
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift", "discount", "promo", "voucher", "onlineApp", "user", "waiter", "pilot"],
    columns: [
      { key: "orderDate", labelEn: "Date", labelAr: "التاريخ", type: "date" },
      { key: "transaction", labelEn: "Transaction", labelAr: "نوع المعاملة", type: "text" },
      { key: "ordersCount", labelEn: "Orders", labelAr: "عدد الطلبات", type: "int", totalKey: "ordersCount" },
      { key: "guestNo", labelEn: "Guests", labelAr: "عدد الضيوف", type: "int", totalKey: "guestNo" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money", totalKey: "totalSales" },
      { key: "totalCommercialDiscount", labelEn: "Commercial Discount", labelAr: "الخصم التجاري", type: "money", totalKey: "totalCommercialDiscount" },
      { key: "totalItemDiscount", labelEn: "Item Discount", labelAr: "خصم الأصناف", type: "money", totalKey: "totalItemDiscount" },
      { key: "extraDiscount", labelEn: "Extra Discount", labelAr: "خصم إضافي", type: "money", totalKey: "extraDiscount" },
      { key: "services", labelEn: "Services", labelAr: "الخدمة", type: "money", totalKey: "services" },
      { key: "totalTax", labelEn: "Tax", labelAr: "الضريبة", type: "money", totalKey: "totalTax" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cash" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visa" },
      { key: "cl", labelEn: "Ledge", labelAr: "آجل", type: "money", totalKey: "cl" },
      { key: "voucherAmount", labelEn: "Voucher", labelAr: "قسيمة", type: "money", totalKey: "voucherAmount" },
      { key: "otherPayment", labelEn: "Other Payment", labelAr: "دفع آخر", type: "money", totalKey: "otherPayment" },
      { key: "net", labelEn: "Net", labelAr: "الصافي", type: "money", totalKey: "net" },
    ],
  },
  "sales-period-by-payment": {
    id: "sales-period-by-payment",
    titleEn: "Sales Period By Payment", titleAr: "مبيعات الفترة حسب طريقة الدفع",
    subtitleEn: "Totals per day × payment method", subtitleAr: "إجماليات لكل يوم × طريقة الدفع",
    endpoint: "DailySalesController/getDailySalesReport", transform: "groupByDayPayment",
    mergeColumn: "orderDate",
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift", "discount", "promo", "voucher", "onlineApp", "user", "waiter", "pilot"],
    columns: [
      { key: "orderDate", labelEn: "Date", labelAr: "التاريخ", type: "date" },
      { key: "paymentStatus", labelEn: "Payment Method", labelAr: "طريقة الدفع", type: "text" },
      { key: "ordersCount", labelEn: "Orders", labelAr: "عدد الطلبات", type: "int", totalKey: "ordersCount" },
      { key: "guestNo", labelEn: "Guests", labelAr: "عدد الضيوف", type: "int", totalKey: "guestNo" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money", totalKey: "totalSales" },
      { key: "totalCommercialDiscount", labelEn: "Commercial Discount", labelAr: "الخصم التجاري", type: "money", totalKey: "totalCommercialDiscount" },
      { key: "totalItemDiscount", labelEn: "Item Discount", labelAr: "خصم الأصناف", type: "money", totalKey: "totalItemDiscount" },
      { key: "extraDiscount", labelEn: "Extra Discount", labelAr: "خصم إضافي", type: "money", totalKey: "extraDiscount" },
      { key: "services", labelEn: "Services", labelAr: "الخدمة", type: "money", totalKey: "services" },
      { key: "totalTax", labelEn: "Tax", labelAr: "الضريبة", type: "money", totalKey: "totalTax" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cash" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visa" },
      { key: "cl", labelEn: "Ledge", labelAr: "آجل", type: "money", totalKey: "cl" },
      { key: "voucherAmount", labelEn: "Voucher", labelAr: "قسيمة", type: "money", totalKey: "voucherAmount" },
      { key: "otherPayment", labelEn: "Other Payment", labelAr: "دفع آخر", type: "money", totalKey: "otherPayment" },
      { key: "net", labelEn: "Net", labelAr: "الصافي", type: "money", totalKey: "net" },
    ],
  },
  "sold-items": {
    id: "sold-items",
    titleEn: "Sold Items", titleAr: "الأصناف المباعة",
    endpoint: "DailySoldItemsReports/DailySoldItemsReport",
    rowsKey: "items", totalsKey: "totals",
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift"],
    columns: [
      { key: "itemId", labelEn: "Item ID", labelAr: "رقم الصنف", type: "int", defaultHidden: true },
      { key: "itemName", labelEn: "Item", labelAr: "الصنف", type: "text" },
      { key: "quantity", labelEn: "Quantity", labelAr: "الكمية", type: "number", totalKey: "quantity" },
      { key: "unitPrice", labelEn: "Unit Price", labelAr: "سعر الوحدة", type: "money", totalKey: "unitPrice" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money", totalKey: "totalSales" },
      { key: "commercialItemDiscount", labelEn: "Commercial Discount", labelAr: "الخصم التجاري", type: "money", totalKey: "commercialItemDiscount" },
      { key: "itemDiscount", labelEn: "Item Discount", labelAr: "خصم الصنف", type: "money", totalKey: "itemDiscount" },
      { key: "itemTax", labelEn: "Tax", labelAr: "الضريبة", type: "money", totalKey: "itemTax" },
      { key: "totalAmount", labelEn: "Total Amount", labelAr: "إجمالي المبلغ", type: "money", totalKey: "totalAmount" },
      { key: "netAmount", labelEn: "Net Amount", labelAr: "صافي المبلغ", type: "money", totalKey: "netAmount" },
    ],
    // Legacy receipt: Item # · Item · Sub Total · Qty · Net.
    receiptColumns: [
      { key: "itemId", en: "Item #", ar: "رقم" },
      { key: "itemName", en: "Item", ar: "الصنف" },
      { key: "totalSales", en: "Sub Total", ar: "الإجمالي" },
      { key: "quantity", en: "Qty", ar: "كمية" },
      { key: "netAmount", en: "Net", ar: "الصافي" },
    ],
  },
  "sold-item-waiter": {
    id: "sold-item-waiter",
    titleEn: "Sold Items by Waiter", titleAr: "الأصناف المباعة حسب الويتر",
    endpoint: "SoldItemsByWaiter/SoldItemsByWaiter",
    rowsKey: "items", totalsKey: "totals",
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift", "waiter"],
    columns: [
      { key: "waiterId", labelEn: "Waiter ID", labelAr: "رقم الويتر", type: "text", defaultHidden: true },
      { key: "waiterName", labelEn: "Waiter", labelAr: "الويتر", type: "text" },
      { key: "itemId", labelEn: "Item ID", labelAr: "رقم الصنف", type: "int", defaultHidden: true },
      { key: "itemName", labelEn: "Item", labelAr: "الصنف", type: "text" },
      { key: "quantity", labelEn: "Quantity", labelAr: "الكمية", type: "number", totalKey: "quantity" },
      { key: "unitPrice", labelEn: "Unit Price", labelAr: "سعر الوحدة", type: "money", totalKey: "unitPrice" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money", totalKey: "totalSales" },
      { key: "commercialItemDiscount", labelEn: "Commercial Discount", labelAr: "الخصم التجاري", type: "money", totalKey: "commercialItemDiscount" },
      { key: "itemDiscount", labelEn: "Item Discount", labelAr: "خصم الصنف", type: "money", totalKey: "itemDiscount" },
      { key: "itemTax", labelEn: "Tax", labelAr: "الضريبة", type: "money", totalKey: "itemTax" },
      { key: "totalAmount", labelEn: "Total Amount", labelAr: "إجمالي المبلغ", type: "money", totalKey: "totalAmount" },
      { key: "netAmount", labelEn: "Net Amount", labelAr: "صافي المبلغ", type: "money", totalKey: "netAmount" },
    ],
    // Legacy receipt: Item # · Item · Waiter · Sub Total · Qty · Net.
    receiptColumns: [
      { key: "itemId", en: "Item #", ar: "رقم" },
      { key: "itemName", en: "Item", ar: "الصنف" },
      { key: "waiterName", en: "Waiter", ar: "الويتر" },
      { key: "totalSales", en: "Sub Total", ar: "الإجمالي" },
      { key: "quantity", en: "Qty", ar: "كمية" },
      { key: "netAmount", en: "Net", ar: "الصافي" },
    ],
  },
  "sold-items-details": {
    id: "sold-items-details",
    titleEn: "Sold Items Details", titleAr: "تفاصيل الأصناف المباعة",
    endpoint: "ItemsSalesDetails/ItemAndModifierSalesDetails",
    rowsKey: "subCategories", totalsKey: null,
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift"],
    columns: [
      { key: "subCategoryId", labelEn: "Sub-Category ID", labelAr: "رقم القسم الفرعي", type: "int", defaultHidden: true },
      { key: "subCategoryName", labelEn: "Sub-Category", labelAr: "القسم الفرعي", type: "text" },
      { key: "quantity", labelEn: "Quantity", labelAr: "الكمية", type: "number" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money" },
    ],
  },
  "SoldItemsSummary": {
    id: "SoldItemsSummary",
    titleEn: "Sold Items Summary", titleAr: "ملخص الأصناف المباعة",
    endpoint: "SoldItem/GetSoldItemsSummary",
    rowsKey: "categories", totalsKey: "totals",
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift"],
    columns: [
      { key: "categoryId", labelEn: "Category ID", labelAr: "معرّف الفئة", type: "int", defaultHidden: true },
      { key: "categoryName", labelEn: "Category", labelAr: "الفئة", type: "text" },
      { key: "totalQuantity", labelEn: "Quantity", labelAr: "الكمية", type: "number", totalKey: "totalQuantity" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money", totalKey: "total" },
    ],
  },
  "TopItems": {
    id: "TopItems",
    titleEn: "Top Items", titleAr: "أكثر الأصناف مبيعاً",
    endpoint: "ItemRanking/TopItems",
    rowsKey: "", totalsKey: null,
    requestExtra: { with: true, topCount: 0, sortByQuantity: false },
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift"],
    columns: [
      { key: "itemId", labelEn: "Item ID", labelAr: "معرّف الصنف", type: "int", defaultHidden: true },
      { key: "itemName", labelEn: "Item", labelAr: "الصنف", type: "text" },
      { key: "quantity", labelEn: "Quantity", labelAr: "الكمية", type: "number" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money" },
    ],
  },
  "worst-Items": {
    id: "worst-Items",
    titleEn: "Worst Items", titleAr: "أقل الأصناف مبيعاً",
    endpoint: "ItemRanking/WorstItems",
    rowsKey: "", totalsKey: null,
    requestExtra: { with: true, topCount: 0, sortByQuantity: false },
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift"],
    columns: [
      { key: "itemId", labelEn: "Item ID", labelAr: "معرّف الصنف", type: "int", defaultHidden: true },
      { key: "itemName", labelEn: "Item", labelAr: "الصنف", type: "text" },
      { key: "quantity", labelEn: "Quantity", labelAr: "الكمية", type: "number" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money" },
    ],
  },
  "cancelled-order-report": {
    id: "cancelled-order-report",
    titleEn: "Cancelled Orders", titleAr: "الطلبات الملغاة",
    endpoint: "CancelledOrdersReports/CancelledOrderReport",
    rowsKey: "reportData", totalsKey: "totals",
    filters: ["payment", "transaction", "shift", "user", "waiter", "pilot", "discount", "onlineApp"],
    columns: [
      { key: "orderId", labelEn: "Order ID", labelAr: "رقم الطلب", type: "int", defaultHidden: true },
      { key: "transaction", labelEn: "Transaction", labelAr: "نوع المعاملة", type: "text" },
      { key: "orderDate", labelEn: "Order Date", labelAr: "تاريخ الطلب", type: "date" },
      { key: "orderTime", labelEn: "Order Time", labelAr: "وقت الطلب", type: "time" },
      { key: "cancelDate", labelEn: "Cancel Date", labelAr: "تاريخ الإلغاء", type: "date" },
      { key: "cancelTime", labelEn: "Cancel Time", labelAr: "وقت الإلغاء", type: "time" },
      { key: "cancelDifference", labelEn: "Cancel Difference", labelAr: "فارق وقت الإلغاء", type: "time" },
      { key: "cancelReason", labelEn: "Cancel Reason", labelAr: "سبب الإلغاء", type: "text" },
      { key: "cancelledByUserId", labelEn: "Cancelled By User", labelAr: "ألغى بواسطة", type: "text", defaultHidden: true },
      { key: "cancelOrderBy", labelEn: "Cancel Order By", labelAr: "جهة الإلغاء", type: "text" },
      { key: "paymentStatus", labelEn: "Payment Status", labelAr: "حالة الدفع", type: "text" },
      { key: "branchName", labelEn: "Branch", labelAr: "الفرع", type: "text" },
      { key: "shiftName", labelEn: "Shift", labelAr: "الوردية", type: "text" },
      { key: "total", labelEn: "Total", labelAr: "الإجمالي", type: "money", totalKey: "total" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money", totalKey: "totalSales" },
      { key: "net", labelEn: "Net", labelAr: "الصافي", type: "money", totalKey: "net" },
      { key: "services", labelEn: "Services", labelAr: "الخدمة", type: "money", totalKey: "services" },
      { key: "totalCommercialDiscount", labelEn: "Commercial Discount", labelAr: "الخصم التجاري", type: "money", totalKey: "totalCommercialDiscount" },
      { key: "totalTax", labelEn: "Tax", labelAr: "الضريبة", type: "money", totalKey: "totalTax" },
      { key: "totalItemDiscount", labelEn: "Item Discount", labelAr: "خصم الأصناف", type: "money", totalKey: "totalItemDiscount" },
      { key: "extraDiscount", labelEn: "Extra Discount", labelAr: "خصم إضافي", type: "money", totalKey: "extraDiscount" },
      { key: "paymentAmount", labelEn: "Payment Amount", labelAr: "قيمة الدفع", type: "money" },
      { key: "voucherAmount", labelEn: "Voucher Amount", labelAr: "قيمة القسيمة", type: "money", totalKey: "voucher" },
      { key: "minimumChargeValue", labelEn: "Minimum Charge", labelAr: "الحد الأدنى", type: "money" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cash" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visa" },
      { key: "cl", labelEn: "Ledge", labelAr: "آجل", type: "money", totalKey: "cl" },
      { key: "additionValue", labelEn: "Addition", labelAr: "الإضافة", type: "money" },
      { key: "waiterName", labelEn: "Waiter", labelAr: "النادل", type: "text" },
      { key: "orderedBy", labelEn: "Ordered By", labelAr: "تم الطلب بواسطة", type: "text" },
      { key: "poiltName", labelEn: "Pilot", labelAr: "الطيار", type: "text" },
      { key: "discountName", labelEn: "Discount", labelAr: "الخصم", type: "text" },
      { key: "onlineAppName", labelEn: "Online App", labelAr: "تطبيق التوصيل", type: "text" },
      { key: "promoCode", labelEn: "Promo Code", labelAr: "كود الخصم", type: "text" },
      { key: "promoCodeValue", labelEn: "Promo Value", labelAr: "قيمة كود الخصم", type: "money", totalKey: "promoCodeAmount" },
      { key: "promoName", labelEn: "Promo Name", labelAr: "اسم البرومو", type: "text" },
      { key: "voucherName", labelEn: "Voucher Name", labelAr: "اسم القسيمة", type: "text" },
      { key: "remarks", labelEn: "Remarks", labelAr: "ملاحظات", type: "text" },
      { key: "mobilePhone", labelEn: "Mobile Phone", labelAr: "رقم الهاتف", type: "text" },
      { key: "tableName", labelEn: "Table", labelAr: "الطاولة", type: "text" },
    ],
  },
  "void-items-report": {
    id: "void-items-report",
    titleEn: "Void Items", titleAr: "الأصناف الملغاة",
    endpoint: "VoidItemsReport/VoidItemsReport",
    rowsKey: "reportData", totalsKey: "totals",
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift", "user", "waiter"],
    columns: [
      { key: "orderId", labelEn: "Order ID", labelAr: "رقم الطلب", type: "int", defaultHidden: true },
      { key: "itemId", labelEn: "Item ID", labelAr: "رقم الصنف", type: "int", defaultHidden: true },
      { key: "itemName", labelEn: "Item Name", labelAr: "اسم الصنف", type: "text" },
      { key: "quantity", labelEn: "Quantity", labelAr: "الكمية", type: "int", totalKey: "quantity" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money", totalKey: "totalSales" },
      { key: "commercialItemDiscount", labelEn: "Commercial Item Discount", labelAr: "الخصم التجاري للصنف", type: "money", totalKey: "commercialItemDiscount" },
      { key: "itemTax", labelEn: "Item Tax", labelAr: "ضريبة الصنف", type: "money", totalKey: "itemTax" },
      { key: "totalAmount", labelEn: "Total Amount", labelAr: "المبلغ الإجمالي", type: "money", totalKey: "totalAmount" },
      { key: "itemDiscount", labelEn: "Item Discount", labelAr: "خصم الصنف", type: "money", totalKey: "itemDiscount" },
      { key: "netAmount", labelEn: "Net Amount", labelAr: "الصافي", type: "money", totalKey: "netAmount" },
      { key: "unitPrice", labelEn: "Unit Price", labelAr: "سعر الوحدة", type: "money", totalKey: "unitPrice" },
      { key: "itemOrModifier", labelEn: "Item Or Modifier", labelAr: "صنف أو إضافة", type: "text" },
      { key: "transaction", labelEn: "Transaction", labelAr: "نوع المعاملة", type: "text" },
      { key: "reason", labelEn: "Reason", labelAr: "السبب", type: "text" },
      { key: "reasonDescription", labelEn: "Reason Description", labelAr: "وصف السبب", type: "text" },
      { key: "branchName", labelEn: "Branch", labelAr: "الفرع", type: "text" },
      { key: "voidDate", labelEn: "Void Date", labelAr: "تاريخ الإلغاء", type: "date" },
      { key: "voidTime", labelEn: "Void Time", labelAr: "وقت الإلغاء", type: "time" },
      { key: "orderDate", labelEn: "Order Date", labelAr: "تاريخ الطلب", type: "date" },
      { key: "orderTime", labelEn: "Order Time", labelAr: "وقت الطلب", type: "time" },
      { key: "paymentStatus", labelEn: "Payment Status", labelAr: "حالة الدفع", type: "text" },
      { key: "shiftId", labelEn: "Shift", labelAr: "الوردية", type: "int", defaultHidden: true },
      { key: "createdBy", labelEn: "Created By", labelAr: "أنشئ بواسطة", type: "text" },
    ],
  },
  "total-pos": {
    id: "total-pos",
    titleEn: "Total POS Sales", titleAr: "إجمالي مبيعات نقاط البيع",
    endpoint: "TotalPOS/GetTotalPosSales",
    rowsKey: "posSales", totalsKey: null,
    defaultOrdersFilter: "Paid",
    filters: ["payment", "transaction", "shift"],
    columns: [
      { key: "posId", labelEn: "POS ID", labelAr: "رقم نقطة البيع", type: "int", defaultHidden: true },
      { key: "posName", labelEn: "POS", labelAr: "نقطة البيع", type: "text", width: 14 },
      { key: "transactionName", labelEn: "Transaction", labelAr: "نوع المعاملة", type: "text" },
      { key: "shiftName", labelEn: "Shift", labelAr: "الوردية", type: "text" },
      { key: "totalOrderNum", labelEn: "Total Orders", labelAr: "عدد الطلبات", type: "int" },
      { key: "totalSales", labelEn: "Total Sales", labelAr: "إجمالي المبيعات", type: "money" },
      { key: "net", labelEn: "Net", labelAr: "الصافي", type: "money" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money" },
      { key: "otherPayments", labelEn: "Other Payments", labelAr: "مدفوعات أخرى", type: "money" },
      { key: "orderNo", labelEn: "Order No", labelAr: "رقم الطلب", type: "int", defaultHidden: true },
    ],
    // Legacy Total POS receipt: ID · Shift · Trans · Cash · Visa · Orders.
    receiptColumns: [
      { key: "posName", en: "POS", ar: "نقطة", maxLen: 4 },
      { key: "shiftName", en: "Shift", ar: "وردية" },
      { key: "transactionName", en: "Trans", ar: "معاملة" },
      { key: "cash", en: "Cash", ar: "نقدي" },
      { key: "visa", en: "Visa", ar: "فيزا" },
      { key: "orderNo", en: "Orders", ar: "طلبات" },
    ],
  },
  "total-discount": {
    id: "total-discount",
    titleEn: "Total Discounts", titleAr: "إجمالي الخصومات",
    endpoint: "TotalDiscount/TotalDiscountReport",
    rowsKey: "discounts", totalsKey: "totals",
    filters: ["payment", "transaction", "shift", "user", "waiter", "discount", "promo", "onlineApp"],
    columns: [
      { key: "discountId", labelEn: "Discount ID", labelAr: "رقم الخصم", type: "int", defaultHidden: true },
      { key: "discountName", labelEn: "Discount Name", labelAr: "اسم الخصم", type: "text" },
      { key: "totalCommercialItemDiscount", labelEn: "Commercial Discount", labelAr: "الخصم التجاري", type: "money", totalKey: "totalCommercialItemDiscount" },
      { key: "totalItemDiscount", labelEn: "Item Discount", labelAr: "خصم الأصناف", type: "money", totalKey: "totalItemDiscount" },
      { key: "tax", labelEn: "Tax", labelAr: "الضريبة", type: "money", totalKey: "tax" },
      { key: "service", labelEn: "Service", labelAr: "الخدمة", type: "money", totalKey: "service" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cash" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visa" },
      { key: "ledge", labelEn: "Ledge", labelAr: "آجل", type: "money", totalKey: "ledge" },
      { key: "total", labelEn: "Total Discount", labelAr: "إجمالي الخصم", type: "money", totalKey: "totalDiscount" },
      { key: "branchName", labelEn: "Branch", labelAr: "الفرع", type: "text" },
      { key: "transactionName", labelEn: "Transaction", labelAr: "نوع المعاملة", type: "text" },
      { key: "onlineAppName", labelEn: "Online App", labelAr: "تطبيق التوصيل", type: "text" },
      { key: "userName", labelEn: "User", labelAr: "المستخدم", type: "text" },
      { key: "payWay", labelEn: "Payment Method", labelAr: "طريقة الدفع", type: "text" },
    ],
  },
  "promo-code-details": {
    id: "promo-code-details",
    titleEn: "Promo Code Details", titleAr: "تفاصيل أكواد الخصم",
    endpoint: "reports/promocodes/detail",
    rowsKey: "days", totalsKey: "grandTotals", transform: "promoFlatten",
    filters: ["payment", "transaction", "shift", "onlineApp", "user", "waiter"],
    columns: [
      { key: "day", labelEn: "Day", labelAr: "اليوم", type: "date" },
      { key: "promoCodeName", labelEn: "Promo Code", labelAr: "كود الخصم", type: "text" },
      { key: "discountName", labelEn: "Discount", labelAr: "الخصم", type: "text" },
      { key: "ordersCount", labelEn: "Orders Count", labelAr: "عدد الطلبات", type: "int", totalKey: "ordersCount" },
      { key: "orderIds", labelEn: "Order #", labelAr: "أرقام الأوردرات", type: "text" },
      { key: "total", labelEn: "Promo Value", labelAr: "قيمة الخصم", type: "money", totalKey: "total" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cash" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visa" },
      { key: "ledge", labelEn: "Ledge", labelAr: "آجل", type: "money", totalKey: "ledge" },
    ],
    // Legacy receipt: Date · Name · Value · Cash · Visa · Ledge (+ the burned Order #s).
    receiptColumns: [
      { key: "day", en: "Date", ar: "التاريخ" },
      { key: "promoCodeName", en: "Name", ar: "الكود" },
      { key: "total", en: "Value", ar: "القيمة" },
      { key: "cash", en: "Cash", ar: "نقدي" },
      { key: "visa", en: "Visa", ar: "فيزا" },
      { key: "ledge", en: "Ledge", ar: "آجل" },
      { key: "orderIds", en: "Order #", ar: "الأوردرات" },
    ],
  },
  "vouchers-details": {
    id: "vouchers-details",
    titleEn: "Vouchers Details", titleAr: "تفاصيل القسائم",
    endpoint: "VouchersReport/detail",
    rowsKey: "days", totalsKey: "grandTotals", transform: "voucherFlatten",
    filters: ["payment", "transaction", "shift", "onlineApp", "user", "waiter"],
    columns: [
      { key: "day", labelEn: "Day", labelAr: "اليوم", type: "date" },
      { key: "voucherCode", labelEn: "Voucher Code", labelAr: "كود القسيمة", type: "text" },
      { key: "vouchersCount", labelEn: "Vouchers Count", labelAr: "عدد القسائم", type: "int", totalKey: "vouchersCount" },
      { key: "distinctOrders", labelEn: "Distinct Orders", labelAr: "عدد الطلبات", type: "int", totalKey: "distinctOrders" },
      { key: "orderIds", labelEn: "Order #", labelAr: "أرقام الأوردرات", type: "text" },
      { key: "totalVoucherAmount", labelEn: "Total Voucher Amount", labelAr: "إجمالي قيمة القسائم", type: "money", totalKey: "totalVoucherAmount" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cash" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visa" },
      { key: "ledge", labelEn: "Ledge", labelAr: "آجل", type: "money", totalKey: "ledge" },
    ],
    // Legacy cashier voucher receipt: Date · Code · Value · Cash · Visa · Ledge
    // (+ the burned Order #s), with a Count / Amount / Cash / Visa / Ledge totals block.
    receiptColumns: [
      { key: "day", en: "Date", ar: "التاريخ" },
      { key: "voucherCode", en: "Code", ar: "الكود" },
      { key: "totalVoucherAmount", en: "Value", ar: "القيمة" },
      { key: "cash", en: "Cash", ar: "نقدي" },
      { key: "visa", en: "Visa", ar: "فيزا" },
      { key: "ledge", en: "Ledge", ar: "آجل" },
      { key: "orderIds", en: "Order #", ar: "الأوردرات" },
    ],
    receiptTotals: [
      { key: "vouchersCount", en: "Count", ar: "العدد" },
      { key: "totalVoucherAmount", en: "Amount", ar: "الإجمالي", emphasize: true },
      { key: "cash", en: "Cash", ar: "نقدي" },
      { key: "visa", en: "Visa", ar: "فيزا" },
      { key: "ledge", en: "Ledge", ar: "آجل" },
    ],
  },
  "sales-expenses": {
    id: "sales-expenses",
    titleEn: "Expenses", titleAr: "المصروفات",
    endpoint: "reports/expenses/detail",
    rowsKey: "items", totalsKey: "summary",
    filters: ["user"],
    columns: [
      { key: "date", labelEn: "Date", labelAr: "التاريخ", type: "date" },
      { key: "description", labelEn: "Description", labelAr: "الوصف", type: "text" },
      { key: "personName", labelEn: "Person Name", labelAr: "اسم الشخص", type: "text" },
      { key: "amount", labelEn: "Amount", labelAr: "المبلغ", type: "money", totalKey: "totalAmount" },
      { key: "exGroup", labelEn: "Expense Group", labelAr: "مجموعة المصروف", type: "text" },
      { key: "exGroupName", labelEn: "Expense Group Name", labelAr: "اسم مجموعة المصروف", type: "text" },
      { key: "exSubGroup", labelEn: "Expense Sub Group", labelAr: "المجموعة الفرعية للمصروف", type: "text" },
      { key: "exSubGroupName", labelEn: "Expense Sub Group Name", labelAr: "اسم المجموعة الفرعية للمصروف", type: "text" },
      { key: "branchId", labelEn: "Branch ID", labelAr: "رقم الفرع", type: "int", defaultHidden: true },
      { key: "branchName", labelEn: "Branch Name", labelAr: "اسم الفرع", type: "text" },
      { key: "createdBy", labelEn: "Created By", labelAr: "أنشئ بواسطة", type: "text" },
    ],
  },
  "total-expenses": {
    id: "total-expenses",
    titleEn: "Total Expenses", titleAr: "إجمالي المصروفات",
    endpoint: "reports/expenses/totals-by-date",
    rowsKey: "totals", totalsKey: "grand",
    filters: ["user"],
    columns: [
      { key: "date", labelEn: "Date", labelAr: "التاريخ", type: "date" },
      { key: "totalAmount", labelEn: "Total Amount", labelAr: "إجمالي المبلغ", type: "money", totalKey: "totalAmount" },
      { key: "count", labelEn: "Count", labelAr: "العدد", type: "int", totalKey: "count" },
    ],
  },
  "sales-reservations": {
    id: "sales-reservations",
    titleEn: "Reservations", titleAr: "الحجوزات",
    endpoint: "reports/reservations/detail",
    rowsKey: "items", totalsKey: "summary",
    filters: ["payment", "shift", "transaction", "user"],
    columns: [
      { key: "orderHeaderId", labelEn: "Order #", labelAr: "رقم الأوردر", type: "int", defaultHidden: true },
      { key: "reservationDate", labelEn: "Reservation Date", labelAr: "تاريخ الحجز", type: "date" },
      { key: "reservationTime", labelEn: "Reservation Time", labelAr: "وقت الحجز", type: "time" },
      { key: "description", labelEn: "Description", labelAr: "ملاحظات", type: "text" },
      { key: "payway", labelEn: "Payway", labelAr: "طريقة الدفع", type: "text" },
      { key: "paymentAmount", labelEn: "Payment Amount", labelAr: "قيمة الدفعة", type: "money", totalKey: "totalReservationAmount" },
      { key: "cash", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cashSum" },
      { key: "visa", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visaSum" },
      { key: "cl", labelEn: "CLedge", labelAr: "آجل", type: "money", totalKey: "clSum" },
      { key: "otherPayment", labelEn: "Other Payment", labelAr: "دفعات أخرى", type: "money", totalKey: "otherPaymentSum" },
      { key: "userId", labelEn: "User ID", labelAr: "معرّف المستخدم", type: "text", defaultHidden: true },
      { key: "userName", labelEn: "User", labelAr: "المستخدم", type: "text" },
      { key: "branchId", labelEn: "Branch ID", labelAr: "معرّف الفرع", type: "int", defaultHidden: true },
      { key: "branchName", labelEn: "Branch", labelAr: "الفرع", type: "text" },
      { key: "shiftId", labelEn: "Shift ID", labelAr: "معرّف الوردية", type: "int", defaultHidden: true },
      { key: "shiftName", labelEn: "Shift", labelAr: "الوردية", type: "text" },
      { key: "transactionId", labelEn: "Transaction ID", labelAr: "معرّف المعاملة", type: "int", defaultHidden: true },
      { key: "transactionName", labelEn: "Transaction", labelAr: "المعاملة", type: "text" },
    ],
  },
  "total-reservations": {
    id: "total-reservations",
    titleEn: "Total Reservations", titleAr: "إجمالي الحجوزات",
    endpoint: "reports/reservations/totals-by-date",
    rowsKey: "totals", totalsKey: "grand",
    filters: ["payment", "shift", "transaction", "user"],
    columns: [
      { key: "reservationDate", labelEn: "Reservation Date", labelAr: "تاريخ الحجز", type: "date" },
      { key: "totalReservationAmount", labelEn: "Total Reservation Amount", labelAr: "إجمالي قيمة الحجوزات", type: "money", totalKey: "totalReservationAmount" },
      { key: "count", labelEn: "Count", labelAr: "العدد", type: "int", totalKey: "count" },
      { key: "cashSum", labelEn: "Cash", labelAr: "نقدي", type: "money", totalKey: "cashSum" },
      { key: "visaSum", labelEn: "Visa", labelAr: "فيزا", type: "money", totalKey: "visaSum" },
      { key: "clSum", labelEn: "CLedge", labelAr: "آجل", type: "money", totalKey: "clSum" },
      { key: "otherPaymentSum", labelEn: "Other Payment", labelAr: "دفعات أخرى", type: "money", totalKey: "otherPaymentSum" },
    ],
  },
  "sales-deferred": {
    id: "sales-deferred",
    titleEn: "CLedge", titleAr: "الآجل",
    endpoint: "reports/CLedges/detail",
    rowsKey: "items", totalsKey: "summary",
    filters: ["shift", "user"],
    columns: [
      { key: "id", labelEn: "ID", labelAr: "المعرّف", type: "int" },
      { key: "payDate", labelEn: "Pay Date", labelAr: "تاريخ الدفع", type: "date" },
      { key: "customerName", labelEn: "Customer Name", labelAr: "اسم العميل", type: "text" },
      { key: "customerMobilePhone", labelEn: "Customer Mobile", labelAr: "موبايل العميل", type: "text" },
      { key: "amount", labelEn: "Amount", labelAr: "المبلغ", type: "money", totalKey: "totalAmount" },
      { key: "userName", labelEn: "User", labelAr: "المستخدم", type: "text" },
      { key: "shiftName", labelEn: "Shift", labelAr: "الوردية", type: "text" },
      { key: "branchName", labelEn: "Branch", labelAr: "الفرع", type: "text" },
      { key: "description", labelEn: "Description", labelAr: "الوصف", type: "text" },
      { key: "exGroupName", labelEn: "Group", labelAr: "المجموعة", type: "text" },
      { key: "exSubGroupName", labelEn: "Sub Group", labelAr: "المجموعة الفرعية", type: "text" },
    ],
  },
  "total-deferred": {
    id: "total-deferred",
    titleEn: "Total CLedge", titleAr: "إجمالي الآجل",
    endpoint: "reports/CLedges/totals-by-date",
    rowsKey: "totals", totalsKey: "grand",
    filters: ["shift", "user"],
    columns: [
      { key: "payDate", labelEn: "Pay Date", labelAr: "تاريخ الدفع", type: "date" },
      { key: "totalAmount", labelEn: "Total Amount", labelAr: "إجمالي المبلغ", type: "money", totalKey: "totalAmount" },
      { key: "count", labelEn: "Count", labelAr: "العدد", type: "int", totalKey: "count" },
    ],
  },
};

export interface ReportNavGroup { titleEn: string; titleAr: string; ids: string[]; }

/** Sidebar grouping for the migrated reports. */
export const REPORT_NAV: ReportNavGroup[] = [
  {
    "titleEn": "Sales",
    "titleAr": "المبيعات",
    "ids": [
      "total-pos"
    ]
  },
  {
    "titleEn": "Daily",
    "titleAr": "اليومي",
    "ids": []
  },
  {
    "titleEn": "Totals",
    "titleAr": "الإجماليات",
    "ids": [
      "salesPeriod",
      "sales-period-by-transaction",
      "sales-period-by-payment"
    ]
  },
  {
    "titleEn": "Items",
    "titleAr": "الأصناف",
    "ids": [
      "sold-items",
      "sold-item-waiter",
      "sold-items-details",
      "SoldItemsSummary",
      "TopItems",
      "worst-Items"
    ]
  },
  {
    "titleEn": "Orders",
    "titleAr": "الطلبات",
    "ids": [
      "cancelled-order-report",
      "void-items-report"
    ]
  },
  {
    "titleEn": "Discounts & Vouchers",
    "titleAr": "الخصومات والقسائم",
    "ids": [
      "total-discount",
      "promo-code-details",
      "vouchers-details"
    ]
  },
  {
    "titleEn": "Expenses",
    "titleAr": "المصروفات",
    "ids": [
      "sales-expenses",
      "total-expenses"
    ]
  },
  {
    "titleEn": "Reservations & CLedge",
    "titleAr": "الحجوزات والآجل",
    "ids": [
      "sales-reservations",
      "total-reservations",
      "sales-deferred",
      "total-deferred"
    ]
  }
];
